name: ci
on: push
jobs:
  # example running all tests on a single machine
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Run Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5

  # example splitting all tests across GitHub machines
  prepare:
    runs-on: ubuntu-20.04
    # explicitly set the output of this job
    # so that other jobs can use it
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      # generate the list using a bash script
      - name: Create matrix ⊹
        id: prepare
        # for reusable workflow, must use the full action reference
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 3 # number of containers to output

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'

  test-split:
    needs: prepare
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Run split Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          DEBUG: cypress-split
          ENVIRONMENT: development
          TEST_AUTOMATION_USERNAME: ${{ secrets.DEV_TEST_AUTOMATION_USERNAME }}
          TEST_AUTOMATION_PASSWORD: ${{ secrets.DEV_TEST_AUTOMATION_PASSWORD }}
          region: ${{ secrets.AWS_COGNITO_REGION }}
          userPoolId: ${{secrets.REACT_APP_USER_POOL_ID}}
          userPoolWebClientId: ${{secrets.REACT_APP_APP_CLIENT_ID}}
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          record: false
  # cypress-run:
  #   # https://github.com/bahmutov/cypress-workflows
  #   uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v1
  #   with:
  #     n: 4
  #   env:
  #     ENVIRONMENT: development
  #     TEST_AUTOMATION_USERNAME: ${{ secrets.DEV_TEST_AUTOMATION_USERNAME }}
  #     TEST_AUTOMATION_PASSWORD: ${{ secrets.DEV_TEST_AUTOMATION_PASSWORD }}
  #     region: ${{ secrets.AWS_COGNITO_REGION }}
  #     userPoolId: ${{secrets.REACT_APP_USER_POOL_ID}}
  #     userPoolWebClientId: ${{secrets.REACT_APP_APP_CLIENT_ID}}
  #     # pass GitHub token to detect new build vs re-run build
  #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #     record: false